### ISSUE TITLE
URL Query String Parameters Required

### ISSUE THREAD

**Issue by robboerman2** [DianaIonita/serverless-api-gateway-caching#11]
<img width="966" alt="schermafbeelding 2018-10-09 om 16 54 48" src="https://user-images.githubusercontent.com/28255308/46678055-19c31f00-cbe4-11e8-9694-1a55d6d3e0ea.png">

Nice plugin! finally i do not have to make a workaround in my resources anymore.
But i still have a small problem with Query strings.

enable caching works without problems but it also makes them required.
Is it also possible to make them not required, but caching turned on?

**Comment by robboerman2** [comment]
created PR to fix this. @DianaIonita could you check it? 
https://github.com/DianaIonita/serverless-api-gateway-caching/pull/12

**Comment by DianaIonita** [comment]
Hey @robboerman2,

Thanks for submitting this issue. If you have a look at the warning in Api Gateway, you'll notice how the Required field doesn't apply to caching but to request validation:

![image](https://user-images.githubusercontent.com/2750493/46757645-a6dca580-ccc2-11e8-93b5-f2d7a1c3c57f.png)

I'll remove the `required` element from this plugin, since it's not related to caching.

**Comment by DianaIonita** [comment]
I just released a new version which won't do anything to the Required field: https://github.com/DianaIonita/serverless-api-gateway-caching/releases/tag/1.1.4

**Comment by robboerman2** [comment]
Oke that is another good solution👍

**Comment by DianaIonita** [comment]
@robboerman2 I'm not familiar with any plugins that do that right now, I only know how to do it via Resources. Nice idea for another plugin 😄
